### ISSUE TITLE
Modli crash on sanitizing against an object definition with no 'keys' prop

### ISSUE THREAD

**Issue by TomFrost** [node-modli/modli#8]
The line in question (as of the time of this writing): https://github.com/node-modli/modli/blob/master/src/lib/model.js#L76

Consider a rule might be defined with `type: 'object'` that either specifies `values` instead of `keys`, or neither of those things (in the case of allowing free-form keys and values). When you attempt to read an object associated with that definition, sanitize() is called and a `TypeError: Cannot read property X of undefined` is thrown as a result.

**Comment by TomFrost** [comment]
(Also worth note... I'd try to fix this myself, but I'd have to sell my damn soul to figure out what the line above that does)

**Comment by Fluidbyte** [comment]
Since Obey is now default, but can be switched out, I've been wondering if it makes sense to retain the `sanitize` method as it exists in the adapters (`read` methods) but relegate it to a return of the data, then use it as a way to "plug in" sanitization based on the requirements of the project.

I feel like, by opening up validation and modeling, it would be hard to maintain this going forward.

**Comment by TomFrost** [comment]
Yeah -- when I suggested pluggable validators, I didn't realize how embedded obey actually was, even within modli-dynamodb. I'm absolutely cool with going all-in on Obey if it means simplifying this sort of thing.

**Comment by Fluidbyte** [comment]
It's not really - at least not as much as Joi. I think we leave it as the default (but easily overwritable as it is now), then cut the `sanitize` method back to a simple return. This will let users easily plug in a sanitize method to handle data alignment on reads but remove opinionation.
